### ISSUE TITLE
Fails on Windows & Sauce Labs

### ISSUE THREAD

**Issue by igoradamenko** [just-boris/wdio-demo#2]
Hello!

I watched your speech on [Ya.Subbotnik](https://events.yandex.ru/lib/talks/3341/) and tried to run your demo on my PC, but I can't.

Some info:
Windows 10, npm v.2.14.20, node v.4.4.0

So, I cloned your repo, `npm install` it. It installed fine, but when I tried to `npm test` I got an error: 

```
$ npm test

> wdio-demo@1.0.0 pretest D:\Dropbox\БГТУ\ТиО ПО\lab3
> rm -rf allure-results


> wdio-demo@1.0.0 test D:\Dropbox\БГТУ\ТиО ПО\lab3
> wdio wdio.conf.js


ERROR: Couldn't connect to selenium server
firefox
    at new RuntimeError (D:\Dropbox\БГТУ\ТиО ПО\lab3\node_modules\webdriverio\bu
ild\lib\utils\ErrorHandler.js:115:12)
    at Request._callback (D:\Dropbox\БГТУ\ТиО ПО\lab3\node_modules\webdriverio\b
uild\lib\utils\RequestHandler.js:264:37)
    at self.callback (D:\Dropbox\БГТУ\ТиО ПО\lab3\node_modules\webdriverio\node_
modules\request\request.js:373:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (D:\Dropbox\БГТУ\ТиО ПО\lab3\node_modules\webdrive
rio\node_modules\request\request.js:971:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)

npm ERR! Test failed.  See above for more details.
```

So.. after an hour :grinning: and tons of rewritings I accidentally changed `host` from `0.0.0.0` to `127.0.0.1` and firefox started to run. But I still got an error; another error.

```
$ npm test

> wdio-demo@1.0.0 pretest d:\Dropbox\БГТУ\ТиО ПО\lab3
> rm -rf allure-results


> wdio-demo@1.0.0 test d:\Dropbox\БГТУ\ТиО ПО\lab3
> wdio wdio.conf.js


.

0 passing (29.10s)
1 failing

1) "before each" hook for "list repositiories":
timeout of 10000ms exceeded. Ensure the done() callback is being called in this
test.
running firefox
Error: timeout of 10000ms exceeded. Ensure the done() callback is being called i
n this test.
    at null.<anonymous> (d:\Dropbox\БГТУ\ТиО ПО\lab3\node_modules\mocha\lib\runn
able.js:215:19)
    at Timer.listOnTimeout (timers.js:92:15)



Wrote Allure report for Organization page to [./allure-results].
npm ERR! Test failed.  See above for more details.
```

Also I tried to use Sauce Labs. I set another host and port, set user and key, but got same error. So I tried to remove [this line](https://github.com/just-boris/wdio-demo/blob/master/test/main.spec.js#L9) and errors had gone!

That's not all. `npm run report` opens browser on `http://192.168.56.1:55964` but can't load any resources except `index.html`. I tried to run `node-static` in `./allure-report` and report was loaded fine. I don't know what's the problem :)

So. I'm not sure that I should to send PR, 'cause your demo may works fine on Mac OS X. But it does not work on Windows. I've described some solutions above and hope it helps. 

Sorry for too long issue.

**Comment by just-boris** [comment]
Thank you for your report! I haven't tested my project on Windows, for sure.

I am going to get a Windows for tests and try to fix this.
