### ISSUE TITLE
Не запускается тест

### ISSUE THREAD

**Issue by awibox** [just-boris/wdio-demo#3]
/Users/andrey/wdio-demo/node_modules/webdriverio/build/lib/cli.js:369
            throw e;
            ^

Error: Selenium server did not start.Another Selenium process may already be running or your java version may be out of date.
    at ChildProcess.errorIfNeverStarted (/Users/andrey/wdio-demo/node_modules/selenium-standalone/lib/start.js:125:15)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! Test failed.  See above for more details.

**Comment by awibox** [comment]
Обновил java - помогло
